-- MySQL Script generated by MySQL Workbench
-- Thu Jun 23 10:54:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cap_softura_peliculas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cap_softura_peliculas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cap_softura_peliculas` DEFAULT CHARACTER SET utf8 ;
USE `cap_softura_peliculas` ;

-- -----------------------------------------------------
-- Table `cap_softura_peliculas`.`catalogo_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cap_softura_peliculas`.`catalogo_categoria` ;

CREATE TABLE IF NOT EXISTS `cap_softura_peliculas`.`catalogo_categoria` (
  `id` INT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(85) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cap_softura_peliculas`.`pelicula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cap_softura_peliculas`.`pelicula` ;

CREATE TABLE IF NOT EXISTS `cap_softura_peliculas`.`pelicula` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `poster` VARCHAR(1000) NOT NULL COMMENT 'url para la imagen',
  `sinopsis` TINYTEXT NOT NULL,
  `clasificacion` VARCHAR(1) NOT NULL DEFAULT 'A',
  `fecha_estreno` DATE NOT NULL,
  `fecha_fin_publicacion` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cap_softura_peliculas`.`pelicula_has_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cap_softura_peliculas`.`pelicula_has_categoria` ;

CREATE TABLE IF NOT EXISTS `cap_softura_peliculas`.`pelicula_has_categoria` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pelicula_id` INT(10) UNSIGNED NOT NULL,
  `catalogo_categoria_id` INT(2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pelicula_has_categoria_pelicula_idx` (`pelicula_id` ASC) ,
  INDEX `fk_pelicula_has_categoria_catalogo_categoria1_idx` (`catalogo_categoria_id` ASC) ,
  CONSTRAINT `fk_pelicula_has_categoria_pelicula`
    FOREIGN KEY (`pelicula_id`)
    REFERENCES `cap_softura_peliculas`.`pelicula` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pelicula_has_categoria_catalogo_categoria1`
    FOREIGN KEY (`catalogo_categoria_id`)
    REFERENCES `cap_softura_peliculas`.`catalogo_categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `cap_softura_peliculas`.`catalogo_categoria`
-- -----------------------------------------------------
START TRANSACTION;
USE `cap_softura_peliculas`;
INSERT INTO `cap_softura_peliculas`.`catalogo_categoria` (`id`, `nombre`) VALUES (1, 'Ciencia ficcion');
INSERT INTO `cap_softura_peliculas`.`catalogo_categoria` (`id`, `nombre`) VALUES (2, 'Fantasia');
INSERT INTO `cap_softura_peliculas`.`catalogo_categoria` (`id`, `nombre`) VALUES (3, 'Accion');

COMMIT;

